/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pandawa;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Sendy
 */
public class Transaksi extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public static int Kode;
    String nama = UserSession.getNama();

    public Transaksi() {
        initComponents();
        Kode = Login.kodeLogin;
        tampil_combo();

        if (Kode == 1) {
            LoginOwner();
        } else if (Kode == 2) {
            LoginKaryawan();
        } else {
            LoginOwner();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void tampil_combo() {
        try {
            Connection con = Config.configDB();
            Statement stt = con.createStatement();
            String sql = "select namaBuah from buah";
            ResultSet res = stt.executeQuery(sql);

            while (res.next()) {
                Object[] ob = new Object[3];
                ob[0] = res.getString(1);

                ComboBuah.addItem((String) ob[0]);
            }
            res.close();
            stt.close();

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void LoginOwner() {
        Transaksi.setEnabled(false);
        Transaksi.setVisible(false);
    }

    private void LoginKaryawan() {
        Transaksi.setEnabled(true);
        Transaksi.setVisible(true);
        Laporan.setEnabled(false);
        Laporan.setVisible(false);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ComboBuah = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        TxtJumlah = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtTotal = new javax.swing.JTextField();
        BtnProses = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Home = new javax.swing.JMenuItem();
        Refresh = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Transaksi = new javax.swing.JMenuItem();
        Buah = new javax.swing.JMenuItem();
        Laporan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Quit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 250));

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 630, 10));

        jLabel3.setFont(new java.awt.Font("Futura Md BT", 0, 36)); // NOI18N
        jLabel3.setText("PANDAWA SHOP");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama Pembeli :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 40));
        jPanel1.add(TxtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 130, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jenis Buah : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, 40));

        ComboBuah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Buah" }));
        jPanel1.add(ComboBuah, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 130, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jumlah (kg) :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, 20));

        TxtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtJumlahActionPerformed(evt);
            }
        });
        jPanel1.add(TxtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 130, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total (Rp.) :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, 20));
        jPanel1.add(TxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 130, 30));

        BtnProses.setText("Proses");
        BtnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProsesActionPerformed(evt);
            }
        });
        jPanel1.add(BtnProses, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 110, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TRANSAKSI");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jMenu1.setText("MAIN");

        Home.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jMenu1.add(Home);

        Refresh.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jMenu1.add(Refresh);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("MENU");

        Transaksi.setText("Transaksi");
        Transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaksiActionPerformed(evt);
            }
        });
        jMenu2.add(Transaksi);

        Buah.setText("Data Buah");
        Buah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuahActionPerformed(evt);
            }
        });
        jMenu2.add(Buah);

        Laporan.setText("Laporan");
        Laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanActionPerformed(evt);
            }
        });
        jMenu2.add(Laporan);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("QUIT");

        Quit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        Quit.setText("Logout");
        Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitActionPerformed(evt);
            }
        });
        jMenu3.add(Quit);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaksiActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Transaksi().setVisible(true);
    }//GEN-LAST:event_TransaksiActionPerformed

    private void LaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Laporan().setVisible(true);
    }//GEN-LAST:event_LaporanActionPerformed

    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_QuitActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_HomeActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Transaksi().setVisible(true);
    }//GEN-LAST:event_RefreshActionPerformed

    private void BuahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuahActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DataBuah().setVisible(true);
    }//GEN-LAST:event_BuahActionPerformed

    private void TxtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtJumlahActionPerformed

    private void BtnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProsesActionPerformed
        // TODO add your handling code here:
        try {
            String mysql = "SELECT * FROM buah WHERE namaBuah='" + ComboBuah.getSelectedItem() + "'";
            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(mysql);
            int stok;
            if (res.next()) {
                stok = res.getInt("stok");
                UserSession.setStok(stok);
            }

            if ((UserSession.getStok() - Integer.parseInt(TxtJumlah.getText())) < 0) {
                JOptionPane.showMessageDialog(null, "Stok buah kurang\n Sisa stok adalah " + UserSession.getStok(), "Data Buah", JOptionPane.INFORMATION_MESSAGE);
            } else {
                String sql = "INSERT INTO konsumen VALUES ( '" + TxtNama.getText() + "', '"
                        + ComboBuah.getSelectedItem() + "', " + TxtTotal.getText() + ", " + TxtJumlah.getText() + ")";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();

                int KurangStok = Integer.parseInt(TxtJumlah.getText());
                String sqlstok = "update buah set stok =" + (UserSession.getStok() - KurangStok) + " where namaBuah = '" + ComboBuah.getSelectedItem() + "'";

                int row = stm.executeUpdate(sqlstok);
                if (row == 1) {
                    JOptionPane.showMessageDialog(null, "Sukses memproses transaksi", "Transaksi", JOptionPane.INFORMATION_MESSAGE);
                    conn.close();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Harap Inputkan Nilai Dengan Benar");
        }
    }//GEN-LAST:event_BtnProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnProses;
    private javax.swing.JMenuItem Buah;
    private javax.swing.JComboBox<String> ComboBuah;
    private javax.swing.JMenuItem Home;
    private javax.swing.JMenuItem Laporan;
    private javax.swing.JMenuItem Quit;
    private javax.swing.JMenuItem Refresh;
    private javax.swing.JMenuItem Transaksi;
    private javax.swing.JTextField TxtJumlah;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
